# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1040, 632)
        Form.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2)
        self.outputComboBox = QtWidgets.QComboBox(Form)
        self.outputComboBox.setStyleSheet("background-color: rgb(255, 123, 35);\n"
"")
        self.outputComboBox.setObjectName("outputComboBox")
        self.outputComboBox.addItem("")
        self.outputComboBox.addItem("")
        self.outputComboBox.addItem("")
        self.gridLayout_3.addWidget(self.outputComboBox, 0, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.imageComboBox1 = QtWidgets.QComboBox(Form)
        self.imageComboBox1.setStyleSheet("background-color: rgb(255, 123, 35);")
        self.imageComboBox1.setObjectName("imageComboBox1")
        self.imageComboBox1.addItem("")
        self.imageComboBox1.addItem("")
        self.imageComboBox1.addItem("")
        self.gridLayout_3.addWidget(self.imageComboBox1, 1, 1, 1, 2)
        self.componentComboBox1 = QtWidgets.QComboBox(Form)
        self.componentComboBox1.setStyleSheet("background-color: rgb(255, 123, 35);")
        self.componentComboBox1.setObjectName("componentComboBox1")
        self.componentComboBox1.addItem("")
        self.componentComboBox1.addItem("")
        self.componentComboBox1.addItem("")
        self.componentComboBox1.addItem("")
        self.componentComboBox1.addItem("")
        self.componentComboBox1.addItem("")
        self.componentComboBox1.addItem("")
        self.gridLayout_3.addWidget(self.componentComboBox1, 1, 3, 1, 1)
        self.slider1 = QtWidgets.QSlider(Form)
        self.slider1.setMaximum(100)
        self.slider1.setOrientation(QtCore.Qt.Horizontal)
        self.slider1.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider1.setTickInterval(0)
        self.slider1.setObjectName("slider1")
        self.gridLayout_3.addWidget(self.slider1, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.ImageComboBox2 = QtWidgets.QComboBox(Form)
        self.ImageComboBox2.setStyleSheet("background-color: rgb(255, 123, 35);")
        self.ImageComboBox2.setObjectName("ImageComboBox2")
        self.ImageComboBox2.addItem("")
        self.ImageComboBox2.addItem("")
        self.ImageComboBox2.addItem("")
        self.gridLayout_3.addWidget(self.ImageComboBox2, 2, 1, 1, 2)
        self.componentComboBox2 = QtWidgets.QComboBox(Form)
        self.componentComboBox2.setStyleSheet("background-color: rgb(255, 123, 35);")
        self.componentComboBox2.setObjectName("componentComboBox2")
        self.componentComboBox2.addItem("")
        self.componentComboBox2.addItem("")
        self.componentComboBox2.addItem("")
        self.componentComboBox2.addItem("")
        self.componentComboBox2.addItem("")
        self.componentComboBox2.addItem("")
        self.componentComboBox2.addItem("")
        self.gridLayout_3.addWidget(self.componentComboBox2, 2, 3, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_2.setTickInterval(0)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_3.addWidget(self.horizontalSlider_2, 2, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.resultButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resultButton.setFont(font)
        self.resultButton.setStyleSheet("background-color: rgb(255, 123, 35);color: rgb(255, 255, 255);")
        self.resultButton.setObjectName("resultButton")
        self.gridLayout.addWidget(self.resultButton, 2, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.graphicsView = PlotWidget(Form)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.graphicsView_2 = PlotWidget(Form)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout.addWidget(self.graphicsView_2, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Mixer Output to:"))
        self.outputComboBox.setItemText(0, _translate("Form", "Choose Output "))
        self.outputComboBox.setItemText(1, _translate("Form", "Output 1"))
        self.outputComboBox.setItemText(2, _translate("Form", "Output 2"))
        self.label_3.setText(_translate("Form", "Component 1:"))
        self.imageComboBox1.setItemText(0, _translate("Form", "Choose Image"))
        self.imageComboBox1.setItemText(1, _translate("Form", "Image 1"))
        self.imageComboBox1.setItemText(2, _translate("Form", "Image 2"))
        self.componentComboBox1.setItemText(0, _translate("Form", "Choose Component"))
        self.componentComboBox1.setItemText(1, _translate("Form", "Magnitude"))
        self.componentComboBox1.setItemText(2, _translate("Form", "Phase"))
        self.componentComboBox1.setItemText(3, _translate("Form", "Real"))
        self.componentComboBox1.setItemText(4, _translate("Form", "Imaginary"))
        self.componentComboBox1.setItemText(5, _translate("Form", "Uni Magnitude"))
        self.componentComboBox1.setItemText(6, _translate("Form", "Uni Phase"))
        self.label_4.setText(_translate("Form", "Component 2:"))
        self.ImageComboBox2.setItemText(0, _translate("Form", "Choose Image"))
        self.ImageComboBox2.setItemText(1, _translate("Form", "Image 1"))
        self.ImageComboBox2.setItemText(2, _translate("Form", "Image 2"))
        self.componentComboBox2.setItemText(0, _translate("Form", "Choose Component"))
        self.componentComboBox2.setItemText(1, _translate("Form", "Magnitude"))
        self.componentComboBox2.setItemText(2, _translate("Form", "Phase"))
        self.componentComboBox2.setItemText(3, _translate("Form", "Real"))
        self.componentComboBox2.setItemText(4, _translate("Form", "Imaginary"))
        self.componentComboBox2.setItemText(5, _translate("Form", "Uni Magnitude"))
        self.componentComboBox2.setItemText(6, _translate("Form", "Uni Phase"))
        self.resultButton.setText(_translate("Form", "Result"))
        self.label_2.setText(_translate("Form", "Output 1:"))
        self.label_5.setText(_translate("Form", "Output 2:"))

from pyqtgraph import PlotWidget
