# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from pyqtgraph import PlotWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 788)
        MainWindow.setStyleSheet("background-color: rgb(40, 40, 40);\n"
                                 "color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setStyleSheet("\n"
                                  "background-color: rgb(255, 123, 35);")
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.imageViewer1 = PlotWidget(self.centralwidget)
        self.imageViewer1.setStyleSheet("background-color: rgb(40,40, 40);")
        self.imageViewer1.setObjectName("imageViewer1")
        self.gridLayout.addWidget(self.imageViewer1, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.browseImage1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.browseImage1.setFont(font)
        self.browseImage1.setStyleSheet("\n"
                                        "background-color: rgb(255, 123, 35);")
        self.browseImage1.setObjectName("browseImage1")
        self.gridLayout_2.addWidget(self.browseImage1, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setStyleSheet("\n"
                                    "background-color: rgb(255, 123, 35);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_4.addWidget(self.comboBox, 0, 0, 1, 1)
        self.graph1 = PlotWidget(self.centralwidget)
        self.graph1.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.graph1.setObjectName("graph1")
        self.gridLayout_4.addWidget(self.graph1, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.browseBtn1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.browseBtn1.setFont(font)
        self.browseBtn1.setAutoFillBackground(False)
        self.browseBtn1.setStyleSheet("\n"
                                      "background-color: rgb(255, 123, 35);")
        self.browseBtn1.setObjectName("browseBtn1")
        self.gridLayout_6.addWidget(self.browseBtn1, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 0, 2, 2, 1)
        self.gridLayout_9.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setStyleSheet("\n"
                                  "background-color: rgb(255, 123, 35);")
        self.label2.setObjectName("label2")
        self.gridLayout_3.addWidget(self.label2, 0, 0, 1, 1)
        self.imageViewer2 = PlotWidget(self.centralwidget)
        self.imageViewer2.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.imageViewer2.setObjectName("imageViewer2")
        self.gridLayout_3.addWidget(self.imageViewer2, 1, 0, 1, 1)
        self.browseImage1_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.browseImage1_2.setFont(font)
        self.browseImage1_2.setStyleSheet("\n"
                                          "background-color: rgb(255, 123, 35);")
        self.browseImage1_2.setObjectName("browseImage1_2")
        self.gridLayout_3.addWidget(self.browseImage1_2, 2, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setStyleSheet("\n"
                                      "background-color: rgb(255, 123, 35);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_2, 0, 0, 1, 1)
        self.graph2 = PlotWidget(self.centralwidget)
        self.graph2.setObjectName("graph2")
        self.gridLayout_5.addWidget(self.graph2, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.browsebtn2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.browsebtn2.setFont(font)
        self.browsebtn2.setStyleSheet("\n"
                                      "background-color: rgb(255, 123, 35);")
        self.browsebtn2.setObjectName("browsebtn2")
        self.gridLayout_7.addWidget(self.browsebtn2, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 2, 0, 1, 1)
        self.mixerBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mixerBtn.setFont(font)
        self.mixerBtn.setStyleSheet("\n"
                                    "background-color: rgb(255, 123, 35);")
        self.mixerBtn.setObjectName("mixerBtn")
        self.gridLayout_9.addWidget(self.mixerBtn, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 26))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuMixer = QtWidgets.QMenu(self.menubar)
        self.menuMixer.setObjectName("menuMixer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuMixer.addSeparator()
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuMixer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "  Image1"))
        self.browseImage1.setText(_translate("MainWindow", "Browse"))
        self.comboBox.setItemText(0, _translate(
            "MainWindow", "Choose Component"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Phase"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Real"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.browseBtn1.setText(_translate("MainWindow", "Browse"))
        self.label2.setText(_translate("MainWindow", "   Image2"))
        self.browseImage1_2.setText(_translate("MainWindow", "Browse"))
        self.comboBox_2.setItemText(0, _translate(
            "MainWindow", "Choose Component "))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Phase"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Real"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.browsebtn2.setText(_translate("MainWindow", "Browse"))
        self.mixerBtn.setText(_translate("MainWindow", "MIXER"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuMixer.setTitle(_translate("MainWindow", "Mixer"))
